=== Alesa95/lenguajes-de-marcas/Tema 10 - XML/series.dtd
<!ELEMENT plataforma (serie)+>
<!ATTLIST plataforma nombre CDATA #REQUIRED>

<!ELEMENT serie (titulo, capitulos)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (#PCDATA)>

=== Alesa95/lenguajes-de-marcas/Tema 10 - XML/series.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="estilos_xml.css"?>

<!DOCTYPE plataforma SYSTEM "series.dtd">

<plataforma nombre="Netflix">
    <serie>
        <titulo>Tenten Kakumei</titulo>
        <capitulos>12</capitulos>
    </serie>
    <serie>
        <titulo>Lycoris Recoil</titulo>
        <capitulos>13</capitulos>
    </serie>
    <serie>
        <titulo>Fruits Basket</titulo>
        <capitulos>18</capitulos>
    </serie>
</plataforma>
